# add this to your configuration.yaml (HA root directory)
modbus:
  - name: trovis
    # modbus tcp to rtu converter (e.g. USR-TCP232-E2)
    type: tcp
    host: 192.168.178.59
    port: 502
    # put readings in separate files for easier handling
    sensors: !include_dir_merge_list trovis557x/sensors/
    binary_sensors: !include_dir_merge_list trovis557x/binary_sensors/
    switches: !include_dir_merge_list trovis557x/switches/
