# Add this to your configuration.yaml (HA root directory)

homeassistant:
  packages:
    trovis:
      input_number:      !include trovis557x/input_numbers.yaml
      input_datetime:    !include trovis557x/input_datetime.yaml
      automation:        !include trovis557x/automations.yaml        # new file!
      template:          !include trovis557x/templates.yaml          # new file!
      sensor statistics: !include trovis557x/statistics.yaml
      # deprecated! sensor main:       !include trovis557x/template_sensors.yaml
      # deprecated! sensor curves:     !include trovis557x/heating_curves.yaml
      # deprecated! template triggers: !include trovis557x/trigger_actions.yaml
      # deprecated! automation triggers: !include trovis557x/trigger_actions.yaml
      # deprecated! automation start:    !include trovis557x/trigger_startup.yaml
      # deprecated! automation update:   !include trovis557x/trigger_updates.yaml

modbus:
  - name: trovis
    type: !secret trovis_connection_type
    host: !secret trovis_ip
    port: !secret trovis_port
    sensors:        !include_dir_merge_list trovis557x/registers/
    binary_sensors: !include_dir_merge_list trovis557x/coils/
    # message_wait_milliseconds: 30
    # timeout: 10
    # delay: 5
