# Add this to your configuration.yaml (HA root directory)

modbus:
  - name: trovis
    type: !secret trovis_connection_type
    host: !secret trovis_ip
    port: !secret trovis_port
    sensors:        !include_dir_merge_list trovis557x/sensors/
    binary_sensors: !include_dir_merge_list trovis557x/binary_sensors/
    switches:       !include_dir_merge_list trovis557x/switches/
    climates:       !include_dir_merge_list trovis557x/climates/

sensor trovis:      !include trovis557x/template_sensors.yaml
sensor trovis_stat: !include trovis557x/statistics.yaml
#please move the code from that file here if you have further input_numbers
#unfortunately, for input_numbers this doesn't work as the 2 lines before:
input_number:       !include trovis557x/input_numbers.yaml
