# .github/workflows/enforce-develop.yml
name: Reject PR's to :main branch

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, labeled, unlabeled, ready_for_review]

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - name: Block PRs to :main unless origin is the :develop branch
        if: ${{ github.event.pull_request.base.ref == 'main' && (github.event.pull_request.head.ref != 'develop' || github.event.pull_request.head.repo.full_name != github.repository) }}
        run: |
          echo "❌ PRs to :main can only be created from the :develop branch."
          echo "👉 Please re-create your PR towards the :develop branch."
          exit 1