name: HACS Validation

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main
  release:
    types:
      - published
      - prereleased
  workflow_dispatch:

jobs:
  hacs:
    name: HACS Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run HACS Validation
        uses: hacs/action@main
        with:
          category: integration
